# Generated by Django 2.2.16 on 2020-11-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='tiele',
            new_name='title',
        ),
    ]
